services:
  database:
    build: ./database
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - umkc-data:/var/lib/mysql
    env_file:
      - .env
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "ping"]
      interval: 8s
      timeout: 8s
      retries: 3

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"

volumes:
  umkc-data: