services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:80"
  database:
    build: ./database
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "umkc-db"
      MYSQL_USER: "umkc"
      MYSQL_PASSWORD: "umkc"
    volumes:
      - umkc-data:/var/lib/mysql
    tty: true
volumes:
  umkc-data: