services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      database:
        # database takes time to start, so we watch a health check
        condition: service_healthy

  database:
    build: ./database
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - umkc-data:/var/lib/mysql
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "ping"]
      interval: 8s
      timeout: 8s
      retries: 3

  frontend:
    build: ./frontend-experiments
    restart: always
    ports:
      - "3000:3000"

volumes:
  umkc-data: